import java.util.Properties

plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeCompiler)
}

/**
 * The Android app shell. Deliberately almost empty: it hosts the shared Compose
 * UI from `:composeApp` and owns nothing but the manifest and the entry Activity.
 */
/**
 * Release signing, read from a gitignored `keystore.properties`.
 *
 * Never checked in and never generated by the build. The upload key is the one
 * credential in this project that cannot be replaced: Play binds a listing to
 * it, so losing it means never updating that listing again. It is the
 * maintainer's to create and to back up, and a build that quietly generated one
 * would be handing out a key nobody knew they had to keep.
 *
 * Absent, the release build stays unsigned rather than failing: `assembleRelease`
 * is also how R8 gets exercised, and that must not need a private key to run.
 */
val signingProps: Properties? =
    rootProject.file("keystore.properties").takeIf { it.exists() }?.let { file ->
        Properties().also { props -> file.inputStream().use(props::load) }
    }

android {
    namespace = "ie.shoonya.vitt"
    compileSdk = libs.versions.androidCompileSdk.get().toInt()

    defaultConfig {
        applicationId = "ie.shoonya.vitt"
        minSdk = libs.versions.androidMinSdk.get().toInt()
        targetSdk = libs.versions.androidTargetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0.0"
    }

    signingConfigs {
        if (signingProps != null) {
            create("release") {
                storeFile = rootProject.file(signingProps.getProperty("storeFile"))
                storePassword = signingProps.getProperty("storePassword")
                keyAlias = signingProps.getProperty("keyAlias")
                keyPassword = signingProps.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            // R8 on, because a shipped build should be shrunk and because the
            // rules are only worth anything if they are the ones that ship.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            signingConfig = signingConfigs.findByName("release")
        }
    }

    // BuildConfig.DEBUG gates the development seeders in MainActivity. AGP 9
    // no longer generates the class unless it is asked for.
    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(project(":composeApp"))
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)
}
