"""Build the website's privacy page from docs/privacy-policy.md.

The markdown stays the single source: this drops its internal drafting note,
fills the placeholders that have a value, and wraps the result in the site's
page. A placeholder with no value yet stops the build rather than going live
as literal braces. Run from the repo root:  python3 tools/site-privacy.py
"""
import re
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs/privacy-policy.md"
OUT = ROOT / "site/privacy/index.html"

# Fill these as they become real (docs/submission-placeholders.md).
VALUES = {
    "POLICY_URL": "https://saieeshward.github.io/vitt/privacy/",
    "POLICY_LAST_UPDATED": "23 September 2026",
    # No mailbox chosen yet; the issue tracker is a real, public way to reach us.
    "PRIVACY_EMAIL": "[github.com/saieeshward/vitt/issues](https://github.com/saieeshward/vitt/issues)",
}

text = SRC.read_text()
# The drafting note is for the maintainer, not the reader.
text = re.sub(r"^\*\*Draft[\s\S]*?\*\*\n\n", "", text, count=1, flags=re.M)
title, _, body = text.partition("\n")
missing = sorted(set(re.findall(r"{{([A-Z_0-9]+)}}", body)) - VALUES.keys())
if missing:
    raise SystemExit(f"unfilled placeholders: {', '.join(missing)}")
body = re.sub(r"{{([A-Z_0-9]+)}}", lambda m: VALUES[m.group(1)], body)
html = markdown.markdown(body, extensions=["tables"])

OUT.write_text(f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>Privacy policy · VITT</title>
  <meta name="description" content="VITT has no server and collects nothing. Your data stays on your device and in a Google Sheet you own.">
  <link rel="icon" href="../assets/img/favicon.png" type="image/png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Geist:wght@400..700&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../assets/css/site.css">
</head>
<body>
  <!-- Generated by tools/site-privacy.py from docs/privacy-policy.md. Edit the markdown, not this. -->
  <header class="nav scrolled">
    <div class="wrap">
      <a class="brand" href="../"><img src="../assets/img/icon-256.png" alt="" width="28" height="28"><span>VITT</span></a>
      <ul><li><a class="link" href="../">Home</a></li><li><a class="link" href="https://github.com/saieeshward/vitt">GitHub</a></li></ul>
    </div>
  </header>
  <main class="doc" id="main">
    <div class="wrap">
      <h1>{title.lstrip('# ').strip()}</h1>
      {html}
    </div>
  </main>
  <footer><div class="wrap"><span>VITT · Apache-2.0 · by <a href="https://github.com/saieeshward">Sai Eeshwar D</a> and <a href="https://github.com/batunii">Shreyansh Soni</a></span><nav aria-label="Footer"><a href="../">Home</a><a href="https://github.com/saieeshward/vitt/issues">Support</a><a href="https://github.com/saieeshward/vitt">Source</a></nav></div></footer>
</body>
</html>
""")
print(f"wrote {OUT.relative_to(ROOT)}")
