"""Copy the companion sprites from the app into the website.

The site's pets are the app's pets, rect for rect: this reads the sprite
strings out of CompanionSprites.kt and Companion.kt and writes them as a JS
module, so redrawing an animal in the app and re-running this is the whole
update. Run from the repo root:  python3 tools/site-pets.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITES = ROOT / "composeApp/src/commonMain/kotlin/ie/shoonya/vitt/ui/CompanionSprites.kt"
COMPANION = ROOT / "composeApp/src/commonMain/kotlin/ie/shoonya/vitt/ui/Companion.kt"
OUT = ROOT / "site/assets/js/pets.js"

src = SPRITES.read_text()
poses = {}
for name, pose, body in re.findall(r'private const val ([A-Z]+)_([A-Z]+) =\s*"([^"]+)"', src):
    rects = []
    for r in body.split("/"):
        x, y, w, h, colour, part = r.split()
        rects.append([int(x), int(y), int(w), int(h), colour, part])
    poses.setdefault(name.lower(), {})[pose.lower()] = rects

meta = {}
for key, label, kind, marker in re.findall(r'[A-Z]+\(\s*"([a-z]+)", "([^"]+)", "([^"]+)", "([^"]+)"', COMPANION.read_text()):
    meta[key] = {"name": label, "kind": kind, "marker": marker}

pets = [{"id": k, **meta[k], "poses": poses[k]} for k in meta if k in poses]
assert len(pets) == 6, [p["id"] for p in pets]
OUT.write_text(
    "// Generated by tools/site-pets.py from the app's CompanionSprites.kt. Do not edit.\n"
    "// Each rect is [x, y, w, h, colour, part] on a 24x20 grid; c0..c5 mean a currency hue.\n"
    "export const PETS = " + json.dumps(pets, separators=(",", ":")) + ";\n"
)
print(f"wrote {OUT.relative_to(ROOT)}: {', '.join(p['name'] for p in pets)}; "
      f"poses {sorted(pets[0]['poses'])}; {OUT.stat().st_size // 1024} KB")
